name: 'Batch Dependabot'
description: 'Batch dependabot'
runs:
  using: "composite"
  steps:
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
      shell: bash  
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash               
    - run: batch.sh
      shell: bash 