name: 'Batch Dependabot'
description: 'Batch dependabot'
runs:
  using: "composite"
  steps:
    - name: install python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9.0' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install pipenv
      run: pip install pipenv
      shell: bash
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
      shell: bash  
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash               
    - run: batch.sh
      shell: bash 